# Generated by Django 4.2.6 on 2023-10-18 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('profiles', '0003_remove_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.company'),
        ),
    ]
